---
- name: Insall Homebrew + troubleshooting command line packages
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  vars:
    # This is overwritten by our group_vars (cpp.build-machines)
    homebrew_installed_packages:
      - htop
      - mc
      - ncdu
  when: not cpp_buildmachine
